<?php

/**
 * 后端数据库server_room_4表模型
 *
 * @SWG\Definition(
 *   definition="ServerRoom4",
 *   description="后端数据库server_room_4表模型",
 *   type="object",
 *   @SWG\Property(
 *       property="id",
 *       type="integer",
 *       format="int32",
 *       example=1,
 *   ),
 *   @SWG\Property(
 *       property="sid",
 *       description="创建此房间的服务器sid",
 *       type="integer",
 *       example=1,
 *   ),
 *   @SWG\Property(
 *       property="ruid",
 *       description="房间唯一标示符",
 *       type="string",
 *       example="1979015395570595113",
 *   ),
 *   @SWG\Property(
 *       property="agent_uid",
 *       description="代理商uid",
 *       type="integer",
 *       example=1,
 *   ),
 *   @SWG\Property(
 *       property="creator_uid",
 *       description="创建人UID",
 *       type="integer",
 *       example=10000,
 *   ),
 *   @SWG\Property(
 *       property="rid",
 *       description="房间id",
 *       type="integer",
 *       example=12345,
 *   ),
 *   @SWG\Property(
 *       property="rtype",
 *       description="游戏类型",
 *       type="integer",
 *       example=4,
 *   ),
 *   @SWG\Property(
 *       property="time",
 *       description="房间创建时间",
 *       type="string",
 *       example="2018-05-04 16:42:55",
 *   ),
 *   @SWG\Property(
 *       property="start_time",
 *       description="回合开始时间",
 *       type="string",
 *       example="2018-05-04 16:42:55",
 *   ),
 *   @SWG\Property(
 *       property="max_round",
 *       description="总回合数",
 *       type="integer",
 *       example=8,
 *   ),
 *   @SWG\Property(
 *       property="cur_round",
 *       description="已结束回合",
 *       type="integer",
 *       example=4,
 *   ),
 *   @SWG\Property(
 *       property="max_cnt",
 *       description="玩家总人数",
 *       type="integer",
 *       example=4,
 *   ),
 *   @SWG\Property(
 *       property="player_cnt",
 *       description="玩家当前人数",
 *       type="integer",
 *       example=2,
 *   ),
 *   @SWG\Property(
 *       property="uid1",
 *       description="玩家1",
 *       type="integer",
 *       example=10000,
 *   ),
 *   @SWG\Property(
 *       property="score_1",
 *       description="玩家1分数",
 *       type="integer",
 *       example=1,
 *   ),
 *   @SWG\Property(
 *       property="uid2",
 *       description="玩家2",
 *       type="integer",
 *       example=10002,
 *   ),
 *   @SWG\Property(
 *       property="score_2",
 *       description="玩家2分数",
 *       type="integer",
 *       example=2,
 *   ),
 *   @SWG\Property(
 *       property="uid3",
 *       description="玩家3",
 *       type="integer",
 *       example=10003,
 *   ),
 *   @SWG\Property(
 *       property="score_3",
 *       description="玩家3分数",
 *       type="integer",
 *       example=3,
 *   ),
 *   @SWG\Property(
 *       property="uid4",
 *       description="玩家4",
 *       type="integer",
 *       example=10004,
 *   ),
 *   @SWG\Property(
 *       property="score_4",
 *       description="玩家4分数",
 *       type="integer",
 *       example=-6,
 *   ),
 *   @SWG\Property(
 *       property="last_time",
 *       description="用来判断此数据是否异常(距离现在超过房间存在时间(3小时))",
 *       type="string",
 *       example="2018-05-26 09:33:20",
 *   ),
 *   @SWG\Property(
 *       property="community_id",
 *       description="牌艺馆id",
 *       type="integer",
 *       example=10009,
 *   ),
 * )
 */